### ISSUE TITLE
Let's get started!

### ISSUE THREAD

**Issue by anthonyLuttrell** [warofants/wwa#1]
I've only created a [README](https://github.com/anthonyLuttrell/wwa/files/3490298/World.War.of.Ants.-.README.docx) file as a guide so far. We'll need to start from scratch building classes for various ant species and then, as a group, determine how we'll proceed from there, creating the mechanics for interactions between ant classes. 

Hopefully this opens a dialogue and we can begin creating this.

**Comment by vinayalaw** [comment]
What kind of game is this? rpg, strategy, colony builder?

**Comment by anthonyLuttrell** [comment]
Right now we're thinking turn-based strategy, but who knows at this point!

**Comment by AlecsisDuarte** [comment]
We could start with an `interface class Ant ` and add methods like `attack`, `defense` and a variable that specifies the ant power or defense values.
We could also create a `class Hive` with an `array`  or number of ants.`

**Comment by RedRoyalDog** [comment]
@vinayalaw The general consensus at the time of this message is that the game will a turn-based strategy focusing on ASCII art. The goal of the game is to allow people to learn game making and coding in a fun and open-source environment.

@AlecsisDuarte Getting started is a great idea! Remember interfaces are used for guaranteeing that a class will have certain functionality. While a class represents the building blocks of a concept such as an Ant. So we could have an abstract base class of an ant that has interfaces such as IAttack, IDefense. etc.

I personally think before we hop into all of that logic we need to get the basics of a game loop going. :)
```
Main Game Loop
    User Input
    Game Logic
    Rendering
``

**Comment by lemikistu** [comment]
Trello board link:https://trello.com/invite/b/xDj6KfHq/372d3221c238af4dbc52cf65659a3c6e/world-war-of-ants

**Comment by uniformfoxtrot** [comment]
I would like to contribute to this, Please let me know what is expected of me...

**Comment by sebriggs14** [comment]
I am pretty new to java and coding in general, and am super stoked to be apart of this project! It sounds like we are going to make classes first based on the different ant and other insect species. I read the README, and was wondering what it is that you are envisioning within the classes. Like what kind of methods? I see excellent information on the differences between the ant species, but how/what do we create based on it?

**Comment by Jacksole** [comment]
I have some experience with Java but I'd like to join this project.  Is this game going to be a player vs a computer or another player

**Comment by cmauf** [comment]
Hello, here I am finally. I connected to the discord and am ready to hop in!

**Comment by anthonyLuttrell** [comment]
Closing/deleting this, nothing useful here
