### ISSUE TITLE
Travis and CircleCI integration

### ISSUE THREAD

**Issue by JeffUTF8** [warofants/wwa#17]
We'll need a .travis.yml file

**Comment by Jacksole** [comment]
I have no problem with Travis CI but any thoughts for or against CircleCI

**Comment by JeffUTF8** [comment]
CircleCI is good too! I'm okay with either. @lemikistu, what are your thoughts?

**Comment by lemikistu** [comment]
I think Travis is best one out there.

**Comment by JeffUTF8** [comment]
I've created a pull request https://github.com/warofants/wwa/pull/36
