### ISSUE TITLE
Issue and Pull Request Template

### ISSUE THREAD

**Issue by Jacksole** [warofants/wwa#25]
Hello Team, I'm just reviewing the community tab under Insights and I think that a template for bug issues and pull request would be a great thing to have. 

It would look like this:
Issue: Bug report 
Create a report to help us improve

Describe the bug

To Reproduce

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

Screenshots

Desktop (please complete the following information):

Smartphone (please complete the following information):

Additional context

Optional additional items
Issue default title:
Assignees:
Labels:

Issue: Feature request 
Suggest an idea for this project

Is your feature request related to a problem? Please describe.

Describe the solution you'd like

Describe alternatives you've considered

Additional context

Optional additional items
Issue default title:
Assignees:
Labels:

**Comment by Veradux** [comment]
Merged
