### ISSUE TITLE
Create small tasks for everyone

### ISSUE THREAD

**Issue by anthonyLuttrell** [warofants/wwa#4]
We need to figure out a way to create very small projects for everyone to contribute. 

Think a worker ant class with static parameters, or parameters from user input

An object like a solider ant that calls a method that will change the parameters of the worker ant

A queen ant that will create more worker or soldier ant classes or objects

Anteaters that will eradicate an entire class

etc..

**Comment by mylesrangel** [comment]
Hey @anthonyLuttrell, as with a lot of others I just joined. In order to get us into a 'flow' where easy tasks and difficult tasks can be easily found we need to use something like trello.com. It can be linked to Github and allows others to assign themselves to cards. It's very good

**Comment by RedRoyalDog** [comment]
@mylesrangel Trello is nice, however, Github has Kanban features natively in the Projects tab. 

https://github.com/anthonyLuttrell/wwa/projects/1

Unfortunately, this may be limited to contributors to the project.

**Comment by lemikistu** [comment]
Trello board link: https://trello.com/invite/b/xDj6KfHq/372d3221c238af4dbc52cf65659a3c6e/world-war-of-ants

**Comment by mylesrangel** [comment]
I think I came off a little forward with that last post. I was suggesting Trello because it allows you to manage non-dev stuff easier imo. Kanban with Github is great as well, especially with linking issues to it.

**Comment by JeffUTF8** [comment]
good news - the trello board is now integrated with github

**Comment by anthonyLuttrell** [comment]
Completed
