### ISSUE TITLE
Entity.java is indented with 3 spaces. change to 4

### ISSUE THREAD

**Issue by root-ansh** [warofants/wwa#66]
![image](https://user-images.githubusercontent.com/31290636/63224981-6e163280-c1e9-11e9-9a4e-0e3c4b6f859e.png)

should i make a pr for it? i have that committed locally in my fork

**Comment by Plat251** [comment]
It's not a very pressing concern at the moment. I think it'd be best resolved when someone actually takes their time to work on Entity.java.

**Comment by root-ansh** [comment]
oh ok, @Plat251 . By the way, if i change this and make a pr, who has the power to merge it?

**Comment by Plat251** [comment]
It's still an on-going issue, so you shouldn't close it - it should be closed only when it's actually fixed.
There is no formal list of people with the power to merge PRs yet, but it should become available tomorrow or the day after tomorrow.

**Comment by root-ansh** [comment]
oh okay

**Comment by daxtery** [comment]
What effect does closing #101 have on this issue? Is it closed?

**Comment by Plat251** [comment]
#101 consists of two commits. The second one completely undoes the changes from first commit. It is inert. Closing it has no effect.

**Comment by RedRoyalDog** [comment]
Someone make a PR to fix this and reference this issue.

**Comment by Plat251** [comment]
Entity.java is not present on development branch due to new architecture. This issue is outdated.
