### ISSUE TITLE
Readme.md is not appropriate to its purpose

### ISSUE THREAD

**Issue by Plat251** [warofants/wwa#7]
A readme.md file is meant to succinctly describe the project itself, its goals, use cases and how to get started. Someone who stumbles upon a project will be presented with readme.md - it is important that they're able to understand what they're looking at, what the purpose is, and how to get involved.

**Comment by morriswr01** [comment]
Agreed but I still think the content of the current readme.md is useful so we should keep it somewhere!

**Comment by Plat251** [comment]
I am currently working on that, preserving the content and drafting up a suitable readme.md.

**Comment by RedRoyalDog** [comment]
Alpha Team has taken this up as a task to improve this a whole bunch :)

**Comment by JeffUTF8** [comment]
Is it ready to close ?

**Comment by anthonyLuttrell** [comment]
Completed
