### ISSUE TITLE
Syncing Trello Board with Github Project

### ISSUE THREAD

**Issue by Jacksole** [warofants/wwa#72]
Just for the sake of synergy(not the right word but only one I can think of). I think that it would be great if we could update the Github Project board to match the one from Trello. Thoughts?

P.S I will be posting this on the Discord Server as well @JaxsonKnight

**Comment by anthonyLuttrell** [comment]
I set it up, but it is a paid power up (5-day free trial). If we prove that we use it, I will consider paying for it long-term
![2019-08-25 06_04_30-Window](https://user-images.githubusercontent.com/53954867/63649045-400b8380-c6fe-11e9-9710-15f3f17a2b96.jpg)
