### ISSUE TITLE
Working on random number gen and related classes.

### ISSUE THREAD

**Issue by anthonyLuttrell** [warofants/wwa#84]
Team November and Team Kilo is going to be working on world.java class and other complementary classes or datatypes like terrain and biomes.

**Comment by anthonyLuttrell** [comment]
➤ Jeff commented:

move to kilo?

**Comment by anthonyLuttrell** [comment]
➤ Desert Fish commented:

jeffutf8 Yeah just found out they were working on the random seed generator for the world map.

**Comment by NishantAcharya** [comment]
Okay, I am assuming this is old

**Comment by daxtery** [comment]
#59
