### ISSUE TITLE
[Team Kilo]Command parser- string to "struct"

### ISSUE THREAD

**Issue by anthonyLuttrell** [warofants/wwa#90]

**Comment by anthonyLuttrell** [comment]
➤ Vinny Desai commented:

Take input string and split each word separated by space into an array to be returned to calling piece of code.

**Comment by anthonyLuttrell** [comment]
➤ Zwei Euro commented:

vinnydesai i think you can take this a step further.
Design tokens that a command must be build out of, and create an object in which the data is stored, this way we can parse a command completely and can (via an enum?) Differentiate what command it is, and get the appropriate data from the object

**Comment by anthonyLuttrell** [comment]
➤ Zwei Euro commented:

vinnydesai i made something like that in cpp, should i post it somewhere? (From a different project)

**Comment by anthonyLuttrell** [comment]
➤ Vinny Desai commented:

Oh dang same. Was it shell code? And yes you can share it to me in discord kakavarna

**Comment by anthonyLuttrell** [comment]
➤ Jeff commented:

vinnydesai is this task complete?

**Comment by anthonyLuttrell** [comment]
➤ Vinny Desai commented:

still needs to be tested so expect it on master in another day.

**Comment by anthonyLuttrell** [comment]
➤ Vinny Desai commented:

jeff submitted for merge.

**Comment by anthonyLuttrell** [comment]
➤ Jeff commented:

vinnydesai nice. move it to the "Merged" list once done

edit: (add your team's name eg. [Team Kilo] at the front)

**Comment by Veradux** [comment]
Implemented by the architecture.
